# Generated by Django 4.2.3 on 2023-08-08 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_category_comment_post_savedposts_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedposts',
            name='posts',
            field=models.ManyToManyField(related_name='users_saved', to='core.post', verbose_name='Saved Post'),
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
